#!/bin/sh

set -eu

export FLASK_APP=/usr/share/uffd/uffd
export CONFIG_PATH=/etc/uffd/uffd.cfg

if [ "$(whoami)" = "uffd" ]; then
	flask "$@"
elif command -v sudo > /dev/null 2>&1; then
	exec sudo --preserve-env=FLASK_APP,CONFIG_PATH -u uffd flask "$@"
elif command -v runuser > /dev/null 2>&1; then
	exec runuser --preserve-environment -u uffd -- flask "$@"
else
	echo "Could not not become 'uffd' user, exiting"
	exit 255
fi
