"""Update remailermode enum

Revision ID: 176473f0a225
Revises: 4bd316207e59
Create Date: 2025-07-25 19:19:20.562732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '176473f0a225'
down_revision = '4bd316207e59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.alter_column('remailer_mode',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('DISABLED', 'ENABLED_V1', 'ENABLED_V2', 'ENABLED_FORWARDER', name='remailermode', create_constraint=True),
               existing_nullable=False)

    with op.batch_alter_table('service_user', schema=None) as batch_op:
        batch_op.alter_column('remailer_overwrite_mode',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('DISABLED', 'ENABLED_V1', 'ENABLED_V2', 'ENABLED_FORWARDER', name='remailermode', create_constraint=True),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_user', schema=None) as batch_op:
        batch_op.alter_column('remailer_overwrite_mode',
               existing_type=sa.Enum('DISABLED', 'ENABLED_V1', 'ENABLED_V2', 'ENABLED_FORWARDER', name='remailermode', create_constraint=True),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.alter_column('remailer_mode',
               existing_type=sa.Enum('DISABLED', 'ENABLED_V1', 'ENABLED_V2', 'ENABLED_FORWARDER', name='remailermode', create_constraint=True),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
