on: workflow_dispatch

jobs:
  publish:
    permissions:
      pages: write
      contents: write
    name: Publish apt repo
    runs-on: ubuntu-latest
    env:
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      KEY_ID: ${{ secrets.KEY_ID }}
      CODENAMES: "bookworm trixie forky"
    steps:
      - name: Install dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get install -y reprepro gnupg jq
      - name: Set up GPG
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          echo "$KEY_ID:6:" |  gpg --batch --import-ownertrust --pinentry-mode=loopback 
          gpg --batch --export "$KEY_ID" --output pubkey.gpg
      - name: Set up APT repo
        run: |
          mkdir -p repo/conf
          for codename in ${CODENAMES}; do
          cat <<EOF >>repo/conf/distributions
          Codename: ${codename}
          Architectures: amd64
          Contents:
          Origin: GitHub
          Label: uffd
          SignWith: ${KEY_ID}

          EOF
          done
          cp pubkey.gpg repo/pubkey.gpg
          touch repo/index.html
      - name: Download all artifacts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export RELEASES="$(gh -R ${{ github.repository }} release list -t "{{ .tagName }}")"
          for release in $RELEASES; do
            echo $release
            rm -rf debtmp || true
            mkdir debtmp
            gh -R ${{ github.repository }} release download --dir debtmp --pattern '*.deb' "$release"
            for codename in ${CODENAMES}; do
              echo "- $codename"
              for f in debtmp/*${codename}*.deb; do
                echo "- - $f"
                reprepro -Vb repo includedeb "$codename" "$f"
              done
            done
          done
      - name: Upload to GitHub pages
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e  # v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./repo
